completed install and uninstall script for service
FlotterCodername/disco pull request #10
Opened 2024-10-14 19:34 UTC by DavidSiegl

First proposed solution for installing and uninstalling disco container as a service.

2024-10-17 23:21 UTC, FlotterCodername reviewed
Very good, clean stuff that simplifies the setup. I did not even know about the `docker service` sub-command.

A few questions relating to how the `run-bot` and `run-bot-debug` scripts currently work:

- Can the PORT_MAPPING and REPLICAS options be made optional? The current bot that is live does not need them at all somehow. It just works.
- I think the ` --volume` option is missing here? The idea is currently to store all application data (configs, db, logs) in `/opt/disco/` on the host and mount that into the container.

2024-10-17 23:21 UTC, FlotterCodername commented on res/scripts/install.sh
> +if [ $? -eq 0 ]; then
```suggestion

if docker service create --name "$SERVICE_NAME" \
  --publish "$PORT_MAPPING" \
  --replicas "$REPLICAS" \
  "$IMAGE_NAME"; then
```
To follow [SC2181](https://github.com/koalaman/shellcheck/wiki/SC2181)

2024-10-17 23:21 UTC, FlotterCodername commented on res/scripts/uninstall.sh
> +if [ $? -eq 0 ]; then
```suggestion

if docker service rm "$SERVICE_NAME"; then
```
to follow [SC2181](https://github.com/koalaman/shellcheck/wiki/SC2181)

2024-10-19 14:56 UTC, DavidSiegl commented
two latest commits should address additional requests

2024-10-24 23:43 UTC, FlotterCodername reviewed
~~Unfortunately, I cannot get it to work~~
Accidentally saved file with CRLF

2024-10-24 23:43 UTC, FlotterCodername commented on res/scripts/install.sh
> +  echo "Usage: $0 -s <service_name> -i <image_name> -v <volume_path> -p (optional) <host_port>:<container_port> -r (optional) <replicas>"
```suggestion
  echo "Usage: $0 -s SERVICE_NAME -i IMAGE_NAME -v VOLUME_PATH [-p HOST_PORT:CONTAINER_PORT] [-r REPLICAS]"
```

2024-10-24 23:43 UTC, FlotterCodername commented on res/scripts/uninstall.sh
> +  echo "Usage: $0 -s <service_name> [-c]"
```suggestion
  echo "Usage: $0 -s SERVICE_NAME [-c]"
```

2024-10-26 18:46 UTC, FlotterCodername requested changes
I noticed that while the service installation completes successfully, there seems to be an issue when running the app as a service through `install.sh`.
I'm wondering if this might be connected to the swarm/replica features? I have never used those myself. Since we're not currently using microservices or load balancing features (which would probably be overkill for our current needs!), we could try simplifying things.

2024-10-26 18:46 UTC, FlotterCodername commented on res/scripts/install.sh
> +
```suggestion
# Copyright © 2024 David Siegl
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
```
Otherwise it's All Rights Reserved

2024-10-26 18:46 UTC, FlotterCodername commented on res/scripts/uninstall.sh
> +
```suggestion
# Copyright © 2024 David Siegl
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
```
Otherwise it's All Rights Reserved

2024-10-27 17:46 UTC, DavidSiegl commented
> I noticed that while the service installation completes successfully, there seems to be an issue when running the app as a service through `install.sh`. I'm wondering if this might be connected to the swarm/replica features? I have never used those myself. Since we're not currently using microservices or load balancing features (which would probably be overkill for our current needs!), we could try simplifying things.

Latest commit simplifies the install/uninstall process and removes the docker service command.

2024-11-02 21:20 UTC, FlotterCodername approved these changes
🚀

2024-11-02 21:21 UTC, merged